#!/usr/bin/env bash
# Tests for: inject-skill.sh (SubagentStart hook)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/../helpers.sh"
setup_test_env

HOOK="$SCRIPT_DIR/../../../hooks/inject-skill.sh"

echo "inject-skill"

# Helper: create an isolated git repo with skills.json
# Overrides HOME to prevent finding real skill files in ~/.claude/skills/
new_repo() {
  REPO_DIR=$(mktemp -d)
  FAKE_HOME=$(mktemp -d)
  cd "$REPO_DIR"
  git init -q -b main
  git config user.email "test@test.com"
  git config user.name "Test"
  git commit --allow-empty -m "init" -q

  mkdir -p .right-hooks
  cat > .right-hooks/skills.json <<'SKILLS'
{
  "codeReview": {
    "skill": "/review",
    "provider": "gstack",
    "fallback": "Dispatch a code review subagent for PR #${PR_NUM}",
    "skillSignature": "Generated by /review"
  },
  "qa": {
    "skill": "/qa",
    "provider": "gstack",
    "fallback": "Dispatch a QA subagent for PR #${PR_NUM}",
    "skillSignature": "Generated by /qa"
  },
  "docConsistency": {
    "skill": "/document-release",
    "provider": "gstack",
    "fallback": "Post a documentation consistency comment on PR #${PR_NUM}",
    "skillSignature": "Documentation health:"
  }
}
SKILLS
}

# Helper: run hook with HOME overridden to prevent finding real skill files
run_isolated_hook() {
  local hook="$1"
  local json_input="$2"
  local stdout_file="$TEST_TMPDIR/stdout"
  local stderr_file="$TEST_TMPDIR/stderr"

  echo "$json_input" | HOME="$FAKE_HOME" RH_TEST=1 bash "$hook" >"$stdout_file" 2>"$stderr_file"
  LAST_EXIT=$?
  LAST_STDOUT="$stdout_file"
  LAST_STDERR="$stderr_file"
}

cleanup_repo() {
  rm -rf "$REPO_DIR" "$FAKE_HOME"
}

# ============================================================
# Fast-exit tests
# ============================================================

# --- Test 1: Fast-exit for empty agent name ---
describe "fast-exits when agent_name is empty"
new_repo
run_isolated_hook "$HOOK" '{"agent_name": ""}'
assert_exit_code 0 "$LAST_EXIT"
STDOUT_CONTENT=$(cat "$LAST_STDOUT" 2>/dev/null)
if [ -z "$STDOUT_CONTENT" ]; then
  pass
else
  fail "Expected empty stdout for empty agent_name, got: $STDOUT_CONTENT"
fi
cleanup_repo

# --- Test 2: Fast-exit for missing agent_name field ---
describe "fast-exits when agent_name field is missing"
new_repo
run_isolated_hook "$HOOK" '{"some_field": "value"}'
assert_exit_code 0 "$LAST_EXIT"
STDOUT_CONTENT=$(cat "$LAST_STDOUT" 2>/dev/null)
if [ -z "$STDOUT_CONTENT" ]; then
  pass
else
  fail "Expected empty stdout for missing agent_name, got: $STDOUT_CONTENT"
fi
cleanup_repo

# --- Test 3: Fast-exit for unknown agent name ---
describe "fast-exits for unknown agent name (no injection)"
new_repo
run_isolated_hook "$HOOK" '{"agent_name": "my-custom-agent"}'
assert_exit_code 0 "$LAST_EXIT"
STDOUT_CONTENT=$(cat "$LAST_STDOUT" 2>/dev/null)
if [ -z "$STDOUT_CONTENT" ]; then
  pass
else
  fail "Expected empty stdout for unknown agent, got: $STDOUT_CONTENT"
fi
cleanup_repo

# --- Test 4: Fast-exit for empty JSON ---
describe "fast-exits for empty JSON input"
new_repo
run_isolated_hook "$HOOK" '{}'
assert_exit_code 0 "$LAST_EXIT"
STDOUT_CONTENT=$(cat "$LAST_STDOUT" 2>/dev/null)
if [ -z "$STDOUT_CONTENT" ]; then
  pass
else
  fail "Expected empty stdout for empty JSON, got: $STDOUT_CONTENT"
fi
cleanup_repo

# ============================================================
# Agent-name-to-gate mapping tests
# ============================================================

# --- Test 5: "reviewer" maps to codeReview gate ---
describe "maps 'reviewer' to codeReview gate (returns systemMessage)"
new_repo
run_isolated_hook "$HOOK" '{"agent_name": "reviewer"}'
assert_exit_code 0 "$LAST_EXIT"
assert_stdout_contains "systemMessage" "$LAST_STDOUT"
cleanup_repo

# --- Test 6: "code-reviewer" alias maps to codeReview gate ---
describe "maps 'code-reviewer' alias to codeReview gate"
new_repo
run_isolated_hook "$HOOK" '{"agent_name": "code-reviewer"}'
assert_exit_code 0 "$LAST_EXIT"
assert_stdout_contains "systemMessage" "$LAST_STDOUT"
cleanup_repo

# --- Test 7: "review" alias maps to codeReview gate ---
describe "maps 'review' alias to codeReview gate"
new_repo
run_isolated_hook "$HOOK" '{"agent_name": "review"}'
assert_exit_code 0 "$LAST_EXIT"
assert_stdout_contains "systemMessage" "$LAST_STDOUT"
cleanup_repo

# --- Test 8: "qa-reviewer" maps to qa gate ---
describe "maps 'qa-reviewer' to qa gate (returns systemMessage)"
new_repo
run_isolated_hook "$HOOK" '{"agent_name": "qa-reviewer"}'
assert_exit_code 0 "$LAST_EXIT"
assert_stdout_contains "systemMessage" "$LAST_STDOUT"
cleanup_repo

# --- Test 9: "qa" alias maps to qa gate ---
describe "maps 'qa' alias to qa gate"
new_repo
run_isolated_hook "$HOOK" '{"agent_name": "qa"}'
assert_exit_code 0 "$LAST_EXIT"
assert_stdout_contains "systemMessage" "$LAST_STDOUT"
cleanup_repo

# --- Test 10: "qa-tester" alias maps to qa gate ---
describe "maps 'qa-tester' alias to qa gate"
new_repo
run_isolated_hook "$HOOK" '{"agent_name": "qa-tester"}'
assert_exit_code 0 "$LAST_EXIT"
assert_stdout_contains "systemMessage" "$LAST_STDOUT"
cleanup_repo

# --- Test 11: "doc-reviewer" maps to docConsistency gate ---
describe "maps 'doc-reviewer' to docConsistency gate (returns systemMessage)"
new_repo
run_isolated_hook "$HOOK" '{"agent_name": "doc-reviewer"}'
assert_exit_code 0 "$LAST_EXIT"
assert_stdout_contains "systemMessage" "$LAST_STDOUT"
cleanup_repo

# --- Test 12: "doc-checker" alias maps to docConsistency gate ---
describe "maps 'doc-checker' alias to docConsistency gate"
new_repo
run_isolated_hook "$HOOK" '{"agent_name": "doc-checker"}'
assert_exit_code 0 "$LAST_EXIT"
assert_stdout_contains "systemMessage" "$LAST_STDOUT"
cleanup_repo

# ============================================================
# Output format tests
# ============================================================

# --- Test 13: Output is valid JSON with systemMessage field ---
describe "output is valid JSON with systemMessage field"
new_repo
run_isolated_hook "$HOOK" '{"agent_name": "reviewer"}'
if jq -e '.systemMessage' "$LAST_STDOUT" >/dev/null 2>&1; then
  pass
else
  fail "Expected valid JSON with systemMessage field"
  echo "    Actual stdout: $(cat "$LAST_STDOUT" 2>/dev/null)"
fi
cleanup_repo

# --- Test 14: systemMessage is a non-empty string ---
describe "systemMessage is a non-empty string"
new_repo
run_isolated_hook "$HOOK" '{"agent_name": "qa-reviewer"}'
MSG_LEN=$(jq -r '.systemMessage | length' "$LAST_STDOUT" 2>/dev/null || echo "0")
if [ "$MSG_LEN" -gt 0 ]; then
  pass
else
  fail "Expected non-empty systemMessage, got length $MSG_LEN"
fi
cleanup_repo

# --- Test 15: Hook always exits 0 (non-blocking) ---
describe "hook always exits 0 for known agents"
new_repo
run_isolated_hook "$HOOK" '{"agent_name": "reviewer"}'
assert_exit_code 0 "$LAST_EXIT"
cleanup_repo

describe "hook always exits 0 for unknown agents"
new_repo
run_isolated_hook "$HOOK" '{"agent_name": "unknown-agent"}'
assert_exit_code 0 "$LAST_EXIT"
cleanup_repo

describe "hook always exits 0 for empty input"
new_repo
run_isolated_hook "$HOOK" '{}'
assert_exit_code 0 "$LAST_EXIT"
cleanup_repo

# ============================================================
# Skill file loading tests
# ============================================================

# --- Test 16: Loads SKILL.md from project-local skills directory ---
describe "loads SKILL.md from .claude/skills/{provider}/SKILL.md"
new_repo
mkdir -p .claude/skills/gstack
printf '# gstack review skill content\nRun the full review workflow.' > .claude/skills/gstack/SKILL.md
run_isolated_hook "$HOOK" '{"agent_name": "reviewer"}'
assert_exit_code 0 "$LAST_EXIT"
assert_stdout_contains "gstack review skill content" "$LAST_STDOUT"
cleanup_repo

# --- Test 17: Loads SKILL.md from skill-name subdirectory ---
describe "loads SKILL.md from .claude/skills/{provider}/{skill_name}/SKILL.md"
new_repo
mkdir -p .claude/skills/gstack/review
printf '# review-specific skill\nDetailed review instructions.' > .claude/skills/gstack/review/SKILL.md
run_isolated_hook "$HOOK" '{"agent_name": "reviewer"}'
assert_exit_code 0 "$LAST_EXIT"
assert_stdout_contains "review-specific skill" "$LAST_STDOUT"
cleanup_repo

# --- Test 18: Falls back to fallback text when skill file not found ---
describe "falls back to skills.json fallback when no SKILL.md"
new_repo
# No .claude/skills directory, HOME overridden — should use fallback from skills.json
run_isolated_hook "$HOOK" '{"agent_name": "reviewer"}'
assert_exit_code 0 "$LAST_EXIT"
assert_stdout_contains "Dispatch a code review subagent" "$LAST_STDOUT"
cleanup_repo

# --- Test 19: Falls back to fallback text for QA gate ---
describe "uses QA fallback text when no skill file"
new_repo
run_isolated_hook "$HOOK" '{"agent_name": "qa-reviewer"}'
assert_exit_code 0 "$LAST_EXIT"
assert_stdout_contains "Dispatch a QA subagent" "$LAST_STDOUT"
cleanup_repo

# --- Test 20: Falls back to fallback text for docConsistency gate ---
describe "uses docConsistency fallback text when no skill file"
new_repo
run_isolated_hook "$HOOK" '{"agent_name": "doc-reviewer"}'
assert_exit_code 0 "$LAST_EXIT"
assert_stdout_contains "documentation consistency comment" "$LAST_STDOUT"
cleanup_repo

# ============================================================
# No skills.json fallback tests
# ============================================================

# --- Test 21: Falls back to generic message when no skills.json ---
describe "falls back to generic message when no skills.json"
REPO_DIR=$(mktemp -d)
FAKE_HOME=$(mktemp -d)
cd "$REPO_DIR"
git init -q -b main
git config user.email "test@test.com"
git config user.name "Test"
git commit --allow-empty -m "init" -q
mkdir -p .right-hooks
# No skills.json — should get generic "Complete the codeReview step" message
run_isolated_hook "$HOOK" '{"agent_name": "reviewer"}'
assert_exit_code 0 "$LAST_EXIT"
assert_stdout_contains "systemMessage" "$LAST_STDOUT"
assert_stdout_contains "codeReview" "$LAST_STDOUT"
cleanup_repo

# --- Test 22: Generic message for QA without skills.json ---
describe "generic message for qa gate without skills.json"
REPO_DIR=$(mktemp -d)
FAKE_HOME=$(mktemp -d)
cd "$REPO_DIR"
git init -q -b main
git config user.email "test@test.com"
git config user.name "Test"
git commit --allow-empty -m "init" -q
mkdir -p .right-hooks
run_isolated_hook "$HOOK" '{"agent_name": "qa-reviewer"}'
assert_exit_code 0 "$LAST_EXIT"
assert_stdout_contains "systemMessage" "$LAST_STDOUT"
assert_stdout_contains "qa" "$LAST_STDOUT"
cleanup_repo

# ============================================================
# Prefers project-local over home directory skill files
# ============================================================

# --- Test 23: Project-local SKILL.md takes priority over home dir ---
describe "project-local SKILL.md takes priority over home dir"
new_repo
mkdir -p .claude/skills/gstack
printf '# LOCAL skill content' > .claude/skills/gstack/SKILL.md
mkdir -p "$FAKE_HOME/.claude/skills/gstack"
printf '# HOME skill content' > "$FAKE_HOME/.claude/skills/gstack/SKILL.md"
run_isolated_hook "$HOOK" '{"agent_name": "reviewer"}'
assert_exit_code 0 "$LAST_EXIT"
assert_stdout_contains "LOCAL skill content" "$LAST_STDOUT"
cleanup_repo

# --- Test 24: Falls back to home dir when project-local missing ---
describe "falls back to home dir SKILL.md when project-local missing"
new_repo
# No project-local skills dir
mkdir -p "$FAKE_HOME/.claude/skills/gstack"
printf '# HOME skill content for fallback' > "$FAKE_HOME/.claude/skills/gstack/SKILL.md"
run_isolated_hook "$HOOK" '{"agent_name": "reviewer"}'
assert_exit_code 0 "$LAST_EXIT"
assert_stdout_contains "HOME skill content for fallback" "$LAST_STDOUT"
cleanup_repo

# ============================================================
# Hook validity test
# ============================================================

# --- Test 25: Hook file is valid bash ---
describe "hook file is valid bash"
bash -n "$HOOK"
assert_exit_code 0 $?

print_summary
